language: python
python:
  - "3.7"
branches:
  only:
    - master
services:
  - redis-server
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U codecov
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - codecov