language: python
python:
  - "3.7"
branches:
  only:
    - master
services:
  - redis-server
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE snakeeyes_test;" -U postgres
  - flask db upgrade
script:
  - pytest
