language: python
python:
  - "3.7"
branches:
  only:
    - master
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pytest
after_success:
  - coveralls
